#!/bin/bash 

function tyaml_parser 
{
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_ -\"]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])(".")}
         printf("%s%s%s:%s\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

get_value()
{
   local file=$1
   local path=$2
   tyaml_parser $file | awk '/^'$path':/{print $0}' | awk -F "$path". '{print $2}'
}

get_keys()
{
   local file=$1
   local path=$2
   tyaml_parser $file | awk '/^'$path'/{print $0}' | awk -F "$path". '{print $2}' | awk -F . '{print $1}' | awk -F : '{print $1}'
}

usage()
{
   echo "usage: tyaml FILE [-k] [-v] argument"
   echo "options:"
   echo "-k: get yaml keys"
   echo "-v: get yaml values"
   echo "example:"
   echo "$ tyaml file.yaml -k option1.values"
}

if [ -n "$2" ]; then
   case "$2" in
      "-v")
         get_value $1 $3
         ;;
      "-k")
         get_keys $1 $3
         ;;
      "-h" | *)
         usage
         exit 0
         ;;
   esac
else
   tyaml_parser $1
fi
