#!/usr/bin/python
import os
import dmenu
import json

MENU_ITEMS = str()
CONFIG_PATH = os.path.join(os.getenv('HOME'), '.config/pymenu.conf')

def get_item(dmenu_command, menu_items):
    for item in menu_items:
        try:
            if dmenu_command == item["name"]:
                return item
        except Exception as error:
            print(error)

def get_command(item):
    command = str()
    try:
        command = item["command"]
    except Exception as error:
        print("Command Error", error)
    return command

def get_callback(item):
    callback = str()
    try:
        callback = item["callback"]
    except Exception as error:
        print("Callback Error", error)
    return callback

def get_name(item):
    name = str()
    try:
        name = item["name"]
    except Exception as error:
        print("Name Error", error)
    return name

def get_confirm_message(item):
    message = str()
    try:
        message = item["confirm"]
    except Exception as error:
        print("Confirm Message Error", error)
    return message

def get_show_confirm(item):
    show = bool(False)
    try:
        if item["confirm"]:
            show = True
    except Exception as error:
        print("Show Confirm", error)
    return show

def get_names(menu_items):
    names_list = list()
    for item in menu_items:
        try:
            names_list.append(item["name"])
        except Exception as error:
            print("Names", error)
    return names_list

def dmenu_show(items, message):
    return dmenu.show(
        items,
        prompt=message,
        background='#1c1f25',
        foreground='#f3f4f5',
        background_selected='#BD93F9',
        foreground_selected='#f3f4f5',
        font="San Francisco Display:size=12"
        )

def apply_command(command_name, items_list):
    item = get_item(command_name, items_list)
    if get_show_confirm(item) == True:
        if dmenu_show(['no', 'yes'], get_confirm_message(item)) == 'yes':
            command = get_command(item)
            os.system(command)
    else:
        command = get_command(item)
        os.system(command)

def load_config(path):
    menu_items = dict()
    try:
        with open(path, 'r') as config_file:
            menu_items = json.load(config_file)
    except FileNotFoundError as exception:
        print(exception)
        menu_items = [{"name": "ConfigFileNotFound"}]
    
    return menu_items


def main():
    MENU_ITEMS = load_config(CONFIG_PATH)
    selected=dmenu_show(get_names(MENU_ITEMS), "Menu")

    apply_command(selected, MENU_ITEMS)

if __name__ == "__main__":
    main()