#!/bin/bash

# Default progress will be counted 5 by 5.
# where 20 '#' will be equal to 100%.

slider_bar=""
slider="[%s]"

lowest=0        # lowest
greatest=100    # greatest
step=5          # step
index_max=0

calculate_index_max()
{
  let index_max=($greatest-$lowest)/$step
  echo $index_max
}

get_index_from_porcentage()
{
  let index=$1*$index_max/$greatest
  [ $index -gt $index_max ] || echo $index && echo $index_max
}

fill_progress()
{
  local index=$1
  for ((i=1; i<= $index; i+=1)); do slider_bar=$slider_bar"#"; done
}

fill_remaining()
{
  local index=$1
  for ((i=$index; i< $index_max; i+=1)); do slider_bar=$slider_bar"-"; done
}

main()
{
  index=$(get_index_from_porcentage $1)
  fill_progress $index
  fill_remaining $index
  printf $slider $slider_bar; printf '\n'
}

usage()
{
  echo "usage: tprogbar [-s <step>] [-l <lowest>] [-g <greatest>] [-v <value>] "
  echo "options:"
  echo "-v: value to be displayed on bar"
  echo "-l: lowest value to be received (default: 0)"
  echo "-g: greatest value to be received (default: 100)"
  echo "-s: step value of the progress bar (default: 5)"
  echo "note that the value argument should be the last one"
  exit 0
}

[[ -z "$@" ]] && usage

while getopts "s:l:g:v:h:" args; do
  case "${args}" in
    s)
      step=${OPTARG}
      ;;
    l)
      lowest=${OPTARG}
      ;;
    g)
      greatest=${OPTARG}
      ;;
    v)
      value=${OPTARG}
      index_max=$(calculate_index_max)
      main $value
      ;;
    * )
      usage
      ;;
    h | help)
      usage
      ;;
  esac
done

