#!/bin/bash 

####################################################################################################
# VARIABLES 
####################################################################################################
MENU_CONFIG_PATH=$1
TYAML_COMMAND="tyaml $MENU_CONFIG_PATH"
menu_prompt=$($TYAML_COMMAND -k)
current_path=$menu_prompt

####################################################################################################
# Functions
####################################################################################################

check_sub_item()
{
  selected_tag=$1
  current_path+=.$selected_tag

  sub_item=$($TYAML_COMMAND -k $current_path)
  
  if [[ -z $sub_item ]];
  then
    command=$($TYAML_COMMAND -v $current_path)
    [ "${command[@]}" != "null" ] && eval "${command[@]}" &
  else
    menu_prompt=$selected_tag
    display_items
  fi
}

display_items()
{
  tag_selected=$($TYAML_COMMAND -k $current_path | dmenu -p $menu_prompt -i)
  [ -z $tag_selected ] || check_sub_item $tag_selected
}

####################################################################################################
# Execute dmenu for the first time
####################################################################################################

display_items
