#!/bin/bash 

####################################################################################################
# VARIABLES 
####################################################################################################
MENU_CONFIG_PATH=$1
TYAML_COMMAND="tyaml $MENU_CONFIG_PATH"

####################################################################################################
# Functions
####################################################################################################

####################################################################################################
# Execute dmenu for the first time
####################################################################################################

menu_prompt=$($TYAML_COMMAND -k)

#           execute tyaml             remove commands   get only tags            pipe to dmenu
selected=$($TYAML_COMMAND -k $menu_prompt | dmenu -p $menu_prompt)

if [[ ! -z $selected ]]; 
then
    command=$($TYAML_COMMAND -v "$menu_prompt.$selected")
    [ "${command[@]}" != "null" ] && eval "${command[@]}" &
    exit 1
fi
