#!/bin/bash

#This file is part of the TinyTools distribution (https://github.com/Calebe94/TinyTools).
#Copyright (C) 2021 TinyTools
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

CONFIG=/etc/tinytools/params.yaml

ENGINE_OPTION=">> CHANGE ENGINE"
PROGRAM_OPTION=">> CHANGE PROGRAM"
CLIP_OPTION=$(echo $(xclip -selection c -o))

ENGINE_CHOICES=$(tsearch -l engine)
PROGRAM_CHOICES=$(tsearch -l program)

PROMPT=$(tsearch -l default.engine)
COMMAND=tsearch
IS_SPECIAL_INPUT=1

if [ -n "$1" ]; then
    PROMPT=$1   
    ENGINE=$1
    COMMAND="$COMMAND -e $ENGINE"
fi

main(){
    while [ $IS_SPECIAL_INPUT == 1 ]; do
        TERM=$(echo -e "$CLIP_OPTION\n$ENGINE_OPTION\n$PROGRAM_OPTION" | dmenu -p "$PROMPT:" -i)
        case "$TERM" in 
            "$ENGINE_OPTION") 
                SELECTED_ENGINE=$(echo -e "$ENGINE_CHOICES" | dmenu -p "Engine:" -i -l 10)
                if [ -n "$SELECTED_ENGINE" ]; then
                    ENGINE="$SELECTED_ENGINE"
                    PROMPT="$ENGINE"
                    COMMAND="$COMMAND -e $ENGINE"
                fi
                IS_SPECIAL_INPUT=1
            ;;
            "$PROGRAM_OPTION") 
                SELECTED_PROGRAM=$(echo -e "$PROGRAM_CHOICES" | dmenu -p "Program:" -i)
                if [ -n "$SELECTED_PROGRAM" ]; then
                    PROGRAM="$SELECTED_PROGRAM"
                    COMMAND="$COMMAND -p $PROGRAM"
                fi
                IS_SPECIAL_INPUT=1
            ;;
            *)
                IS_SPECIAL_INPUT=0
            ;;
        esac
    done
    if [ -n "$TERM" ]; then
        $COMMAND -t "$TERM"  
    fi
}

main
