#!/bin/bash

# Default progress will be counted 5 by 5.
# where 20 '#' will be equal to 100%.

MIN=0
MAX=20

slider_bar=""
slider="[%s]"

get_index_from_porcentage()
{
  let index=$1*20/100
  echo $index
}

fill_progress()
{
  local index=$1
  for ((i=1; i<= $index; i+=1)); do slider_bar=$slider_bar"#"; done
}

fill_remaining()
{
  local index=$1
  for ((i=$index; i< $MAX; i+=1)); do slider_bar=$slider_bar"-"; done
}

index=$(get_index_from_porcentage $1)

main()
{
  index=$(get_index_from_porcentage $1)

  fill_progress $index
  fill_remaining $index
  printf $slider $slider_bar; printf '\n'
}

usage()
{
  echo "usage: tslidepar [value]"
}

[ ! -z $1 ] && main $1 || usage
