#!/usr/bin/bash
#Copyright (C) 2021 TinyTools

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, version 3 of the License.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

note_metadata="---\ntitle: %s\nsubtitle: %s\ndate: %s\ntags: [%s]\n\n---"
note=""
action=""
metadata=0

create_note()
{
    echo "creating note..."
    path=$(dirname $note)
    note_name=$(basename $note)
    [ -f "$note" ] && echo "note already exists!" && exit 1
    [ -d "$path" ] || mkdir "$path"
    echo "# $note_name" > "$note"

    echo "$note_name created!"
}

usage()
{
    echo "usage:"
    exit 0
}

parse_arguments()
{
    # https://stackoverflow.com/a/31443098
    while [ "$#" -gt 0 ]; do
        case "$1" in
            -c | --create | create ) [ ! -z "$2" ] && [ -z "$note" ] && note="$2"; shift ;;
            --subtitle=* | subtitle=* ) subtitle="${1#*=}"; shift ;;
            --tags=* | tags=* )  tags="${1#*=}"; shift ;;
            --title=* | title=* ) title="${1#*=}"; shift ;;
            -m | --metadata | metadata) [ ! -z "$2" ] && metadata=1; shift ;;
            -h | --help | help) usage; shift ;;
            -*) 
                echo "unknown option: $1" >&2; exit 1;;
            *) PARAMS="$PARAMS $1"; shift ;;
        esac
    done
}

arguments="$@"
[ -z "$arguments" ] && usage || parse_arguments "$@"
echo $note
echo $metadata
echo $subtitle
echo $tags
echo $title
if [ -z "$note" ]; then
    echo "deve informar um path"
elif [ -f "$note" ]; then
    echo "nota já existe"
else
    echo "cria nota"
fi
