#!/bin/bash

main_prompt="Repositories"
git_options="open\nstatus\ndiff\ncheckout"

branches_menu(){
    branches="$(cd $path && git branch -r)"
    branch=$(echo -e "$branches" | dmenu -i -p Checkout:)
    x-terminal-emulator -e 'sh -c "cd '$path' && git '$option $branch'; $SHELL"'
}

options_menu(){
    [[ -n $repo ]] || return 1
    path="$HOME/$repo"
    prompt="$(tgit_status $path) $repo"    
    option=$(echo -e "$git_options" | dmenu -i -p "$prompt:")
    [[ -n $option ]] || return 1
    case "$option" in
        "checkout")
            # branches_menu
        ;;
        "open")
            codium $path
        ;;
        *)
            x-terminal-emulator -e 'sh -c "cd '$path' && git '$option'; $SHELL"'
        ;;
    esac
    return 0
}

repos_menu(){
    repo=""
    repo=$(echo -e ">> UPDATE\n$(tgit)" | dmenu -i -p "$main_prompt": | awk '{print $2}')
    [[ -n $repo ]] || exit
    [[ $repo == "UPDATE" ]] && tgit -u && return 1
    return 0
}

while true; do
    repos_menu && break
done

options_menu


