#!/bin/bash

tgit="/home/gabo/packages/tinytools/tgit/tgit"
repo=$(echo -e "$($tgit)" | dmenu -i -p Repos: | awk '{print $2}')

[[ -n $repo ]] || exit
path="$HOME/$repo"
prompt=$(echo "$repo" | awk -F'/' 'NF>1{print $(NF)}') && prompt="$prompt [$($check_status $path)]:"
options="status\ndiff\ncheckout"
option=$(echo -e "$options" | dmenu -i -p "$prompt")

[[ -n $option ]] || exit
case "$option" in
    "checkout")
        branches="$(cd $path && git branch -r)"
        branch=$(echo -e "$branches" | dmenu -i -p Checkout:)
        x-terminal-emulator -e 'bash -c "cd '$path' && git '$option $branch'; zsh"'
    ;;
    *)
        x-terminal-emulator -e 'bash -c "cd '$path' && git '$option'; zsh"'
    ;;
esac