#!/bin/bash

check_status="/home/gabo/packages/tinytools/tgit/check_status"
repos=$(find $HOME -name ".git" | awk -F/ 'BEGIN { OFS = FS } NF{NF-=1};1')

list() {
    for i in $repos
    do
        cd $i
        if [[ "$(git rev-parse --git-dir)" == ".git" ]]; then
            status=$($check_status $i)
            name="${i/"$HOME/"/''}"
            list="$list\n[$status] $name"
        fi
    done
    tmpfile=$(mktemp)
    echo -e "$list" >> $tmpfile
    list=$(column $tmpfile -t)
    rm "$tmpfile"
    echo -e "$list"
}

list 